version: '2'
services:
  web:
    image: ${DOCKER_REG_PRIVATE}/orcid/orcid-web:${TAG:-1}
    entrypoint: sleep infinity
    build:
      dockerfile: orcid-web/Dockerfile
      context: .
      args:
        tag: ${TAG:-1}

