name: maven_test_artifact

# run maven tests and upload results as an artifact
# can be run from a pr

permissions:
  checks: write
  contents: read
  issues: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      context:
        description: 'Name of the context in the repo'
        required: false
        default: "."
        type: string

  workflow_dispatch:
    inputs:
      context:
        description: 'Name of the context in the repo'
        required: false
        default: "."
        type: string

jobs:
  maven_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Open JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: install orcid-test into our local maven repo because the builds depend a version release
        run: |
          mvn -T 1C --batch-mode install -DskipTests \
                    -DnewVersion="$version_tag_numeric" -DgenerateBackupPoms=false -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                    --projects orcid-test

      - name: install orcid-utils into our local maven repo because the builds depend a version release
        run: |
          mvn -T 1C --batch-mode clean install -DskipTests \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              --projects orcid-utils

      - name: "Test ${{ inputs.context }}"
        run: |
          mvn -T 1C --batch-mode -Dmaven.test.failure.ignore=true test \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              --projects ${{ inputs.context }}

      - uses: actions/upload-artifact@v3  # upload test results
        if: success() || failure()        # run this step even if previous step failed
        with:
          name: ${{ inputs.context }}
          path: ${{ inputs.context }}/target/surefire-reports/*.xml
