name: pull_test

on:
  workflow_call:
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: $default-branch


      - name: git pull to include any pipeline made changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git pull

